[package]
name = "npm-rs"
version = "0.1.0"
authors = [""]
edition = "2018"

[lib]
name = "npm_rs"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.10"
semver = "0.9.0"
which = "3.1.0"
fs_extra = "1.1.0"