[package]
name = "npm-rs"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.10"
semver = "0.9.0"
which = "3.1.0"
fs_extra = "1.1.0"